import io
import tempfile
import os
from typing import Optional
import pandas as pd
import plotly.graph_objects as go
from fpdf import FPDF

# ---------------------------------------------------------------------------
# Unicode sanitiser — fpdf2 Helvetica only supports latin-1 range
# ---------------------------------------------------------------------------

def s(text: str) -> str:
    """Strips characters outside latin-1 range to prevent Helvetica font errors."""
    return str(text).encode("latin-1", errors="replace").decode("latin-1")


# ---------------------------------------------------------------------------
# Colours (matching dashboard theme)
# ---------------------------------------------------------------------------
NEST_BLUE  = (31, 60, 136)    # #1f3c88
NEST_RED   = (230, 57, 70)    # #e63946
LIGHT_GRAY = (245, 245, 245)
MID_GRAY   = (180, 180, 180)
WHITE      = (255, 255, 255)
DARK_TEXT  = (30, 30, 30)


# ---------------------------------------------------------------------------
# PDF class with helpers
# ---------------------------------------------------------------------------

class NeSTPDF(FPDF):

    def header(self):
        # Blue top bar
        self.set_fill_color(*NEST_BLUE)
        self.rect(0, 0, 210, 12, "F")
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*WHITE)
        self.set_xy(10, 2)
        self.cell(0, 8, "NeST Digital Academy - L&D Analytics Report", align="L")
        self.set_xy(0, 2)
        self.cell(200, 8, f"Page {self.page_no()}", align="R")
        self.ln(10)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(*MID_GRAY)
        self.cell(0, 8, "Generated by NeST Dashboard · Confidential", align="C")

    def section_title(self, text: str):
        self.ln(4)
        self.set_fill_color(*NEST_BLUE)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 8, f"  {text}", fill=True, ln=True)
        self.ln(3)

    def sub_title(self, text: str):
        self.set_text_color(*NEST_BLUE)
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 6, text, ln=True)
        self.set_text_color(*DARK_TEXT)
        self.ln(1)

    def body_text(self, text: str):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*DARK_TEXT)
        self.multi_cell(0, 5, text)
        self.ln(1)

    def stat_row(self, label: str, value: str, shade: bool = False):
        if shade:
            self.set_fill_color(*LIGHT_GRAY)
        else:
            self.set_fill_color(*WHITE)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*DARK_TEXT)
        self.cell(80, 7, f"  {label}", fill=True, border=1)
        self.set_font("Helvetica", "", 9)
        self.cell(110, 7, f"  {value}", fill=True, border=1, ln=True)

    def table_header(self, cols: list, widths: list):
        self.set_fill_color(*NEST_BLUE)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 8)
        for col, w in zip(cols, widths):
            self.cell(w, 7, f" {col}", fill=True, border=1)
        self.ln()
        self.set_text_color(*DARK_TEXT)

    def table_row(self, values: list, widths: list, shade: bool = False):
        if shade:
            self.set_fill_color(*LIGHT_GRAY)
        else:
            self.set_fill_color(*WHITE)
        self.set_font("Helvetica", "", 8)
        for val, w in zip(values, widths):
            self.cell(w, 6, f" {str(val)}", fill=True, border=1)
        self.ln()


# ---------------------------------------------------------------------------
# Chart → PNG bytes using kaleido
# ---------------------------------------------------------------------------

def fig_to_png(fig: go.Figure, width: int = 700, height: int = 350) -> Optional[bytes]:
    """Converts a Plotly figure to PNG bytes via kaleido."""
    try:
        return fig.to_image(format="png", width=width, height=height, scale=2)
    except Exception as e:
        print(f"[exporter] Warning: could not render chart - {e}")
        return None


def add_chart_to_pdf(pdf: NeSTPDF, fig: go.Figure, title: str = "", width_mm: int = 180):
    """Renders a Plotly figure and embeds it in the PDF."""
    png_bytes = fig_to_png(fig)
    if png_bytes is None:
        pdf.body_text(f"[Chart unavailable: {title}]")
        return

    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        tmp.write(png_bytes)
        tmp_path = tmp.name

    try:
        if title:
            pdf.sub_title(title)
        # Centre the image on the page
        x = (210 - width_mm) / 2
        # Height proportional to 700x350 aspect ratio
        height_mm = width_mm * 350 / 700
        # Page break if not enough space
        if pdf.get_y() + height_mm > 270:
            pdf.add_page()
        pdf.image(tmp_path, x=x, w=width_mm)
        pdf.ln(3)
    finally:
        os.unlink(tmp_path)


# ---------------------------------------------------------------------------
# Summary stats helpers
# ---------------------------------------------------------------------------

def course_summary(activities_df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for course in sorted(activities_df["course"].dropna().unique()):
        cdf = activities_df[activities_df["course"] == course]
        total     = len(cdf)
        completed = (cdf["status"] == "Completed").sum()
        students  = cdf["email"].nunique()
        internal  = cdf.drop_duplicates("email").query("student_type == 'Internal'").shape[0]
        external  = cdf.drop_duplicates("email").query("student_type == 'External'").shape[0]
        inactive  = (
            cdf.groupby("email")["status"]
            .apply(lambda x: (x == "Completed").sum() == 0)
            .sum()
        )
        rate = round(100 * completed / total, 1) if total else 0
        rows.append({
            "Course":            course,
            "Students":          students,
            "Completion Rate":   f"{rate}%",
            "Internal":          internal,
            "External":          external,
            "Inactive Students": inactive,
        })
    return pd.DataFrame(rows)


def activity_breakdown(activities_df: pd.DataFrame, course: str) -> pd.DataFrame:
    cdf = activities_df[activities_df["course"] == course]
    result = (
        cdf.groupby(["activity_category", "activity_name"])
        .agg(
            students  = ("email", "nunique"),
            completed = ("status", lambda x: (x == "Completed").sum()),
        )
        .reset_index()
    )
    result["completion_%"] = (
        100 * result["completed"] / result["students"]
    ).round(1).astype(str) + "%"
    return result.sort_values(["activity_category", "completion_%"], ascending=[True, False])


def at_risk_students(activities_df: pd.DataFrame) -> pd.DataFrame:
    exclude = {"Certificate", "Feedback", "Misc", "Other"}
    core = activities_df[~activities_df["activity_category"].isin(exclude)]
    prog = (
        core.groupby(["email", "student_name", "course"])
        .agg(total=("activity_name", "count"), done=("status", lambda x: (x == "Completed").sum()))
        .reset_index()
    )
    prog["rate"] = (100 * prog["done"] / prog["total"]).round(1)
    return (
        prog[(prog["done"] > 0) & (prog["rate"] < 80)]
        .sort_values("rate")
        .head(30)
    )


# ---------------------------------------------------------------------------
# Main PDF builder
# ---------------------------------------------------------------------------

def build_pdf_report(activities_df: pd.DataFrame) -> bytes:
    """
    Builds a full multi-page PDF report including:
      - Cover page
      - Executive summary with key metrics
      - Per-course sections with charts + activity breakdown tables
      - At-risk students table
    Returns the PDF as bytes.
    """
    from components.charts import (
        chart_students_per_course,
        chart_student_type_split,
        chart_completion_rate_per_course,
        chart_completion_funnel,
        chart_submissions_over_time,
        chart_inactive_students,
        chart_completion_by_category,
    )

    pdf = NeSTPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(10, 15, 10)

    # ── Cover page ────────────────────────────────────────────────────────
    pdf.add_page()
    pdf.set_fill_color(*NEST_BLUE)
    pdf.rect(0, 0, 210, 297, "F")

    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(*WHITE)
    pdf.set_xy(0, 80)
    pdf.cell(210, 14, "NeST Digital Academy", align="C", ln=True)

    pdf.set_font("Helvetica", "", 16)
    pdf.set_xy(0, 100)
    pdf.cell(210, 10, "L&D Platform - Analytics Report", align="C", ln=True)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(180, 200, 240)
    pdf.set_xy(0, 118)
    pdf.cell(210, 8, "Activity Reports · Student Enrollment · Completion Analysis", align="C", ln=True)

    # Stats block on cover
    summary_df = course_summary(activities_df)
    total_students = activities_df["email"].nunique()
    avg_rate = round(
        100 * (activities_df["status"] == "Completed").sum() / len(activities_df), 1
    )

    pdf.set_fill_color(255, 255, 255, )
    pdf.set_xy(30, 150)
    pdf.set_font("Helvetica", "B", 36)
    pdf.set_text_color(*WHITE)
    pdf.cell(50, 20, str(total_students), align="C")
    pdf.cell(50, 20, "4", align="C")
    pdf.cell(50, 20, f"{avg_rate}%", align="C")
    pdf.ln()
    pdf.set_xy(30, 170)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(180, 200, 240)
    pdf.cell(50, 8, "Total Students", align="C")
    pdf.cell(50, 8, "Courses", align="C")
    pdf.cell(50, 8, "Avg Completion", align="C")

    # ── Executive Summary ─────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Executive Summary")

    pdf.sub_title("Platform Overview")
    pdf.stat_row("Total Students",        str(activities_df["email"].nunique()), shade=False)
    pdf.stat_row("Total Courses",         "4", shade=True)
    pdf.stat_row("Total Activity Records", f"{len(activities_df):,}", shade=False)
    pdf.stat_row("Overall Completion Rate", f"{avg_rate}%", shade=True)
    internal = activities_df.drop_duplicates("email").query("student_type == 'Internal'").shape[0]
    external = activities_df.drop_duplicates("email").query("student_type == 'External'").shape[0]
    pdf.stat_row("Internal Students",     str(internal), shade=False)
    pdf.stat_row("External Students",     str(external), shade=True)
    pdf.ln(4)

    pdf.sub_title("Course Summary")
    cols   = ["Course", "Students", "Completion Rate", "Internal", "External", "Inactive"]
    widths = [50, 25, 35, 25, 25, 30]
    pdf.table_header(cols, widths)
    for i, row in summary_df.iterrows():
        pdf.table_row([
            row["Course"], row["Students"], row["Completion Rate"],
            row["Internal"], row["External"], row["Inactive Students"]
        ], widths, shade=(i % 2 == 0))
    pdf.ln(4)

    # Overview charts
    add_chart_to_pdf(pdf, chart_students_per_course(activities_df),       "Students per Course")
    add_chart_to_pdf(pdf, chart_completion_rate_per_course(activities_df), "Completion Rate by Course")
    add_chart_to_pdf(pdf, chart_student_type_split(activities_df),         "Student Type Breakdown")
    add_chart_to_pdf(pdf, chart_completion_by_category(activities_df),     "Completion Rate by Activity Category")
    add_chart_to_pdf(pdf, chart_submissions_over_time(activities_df),      "Completions Over Time (Weekly)")
    add_chart_to_pdf(pdf, chart_inactive_students(activities_df),          "Inactive Students per Course")

    # ── Per-course sections ───────────────────────────────────────────────
    for course in sorted(activities_df["course"].dropna().unique()):
        pdf.add_page()
        pdf.section_title(f"{course} - Detailed Report")

        cdf = activities_df[activities_df["course"] == course]
        total     = len(cdf)
        completed = (cdf["status"] == "Completed").sum()
        students  = cdf["email"].nunique()
        rate      = round(100 * completed / total, 1) if total else 0

        pdf.stat_row("Total Students",    s(str(students)),  shade=False)
        pdf.stat_row("Completion Rate",   s(f"{rate}%"),     shade=True)
        pdf.stat_row("Total Activities",  s(str(total)),     shade=False)
        pdf.stat_row("Completed Activities", s(str(completed)), shade=True)
        pdf.ln(4)

        # Funnel chart for this course
        add_chart_to_pdf(pdf, chart_completion_funnel(activities_df, course), f"Completion Funnel - {course}")

        # Activity breakdown table
        pdf.sub_title("Activity Breakdown")
        act_df = activity_breakdown(activities_df, course)
        cols   = ["Category", "Activity", "Students", "Completed", "Rate"]
        widths = [30, 80, 22, 25, 33]
        pdf.table_header(cols, widths)
        for i, row in act_df.iterrows():
            # Truncate long activity names
            act_name = str(row["activity_name"])[:55] + "..." if len(str(row["activity_name"])) > 55 else str(row["activity_name"])
            pdf.table_row([
                s(row["activity_category"]),
                s(act_name),
                s(str(row["students"])),
                s(str(row["completed"])),
                s(row["completion_%"]),
            ], widths, shade=(i % 2 == 0))

    # ── At-risk students ──────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("At-Risk Students")
    pdf.body_text(
        "Students who have started at least one core activity but have completed less than 80% "
        "of their course. These students may benefit from follow-up or additional support."
    )

    at_risk = at_risk_students(activities_df)
    if at_risk.empty:
        pdf.body_text("No at-risk students identified.")
    else:
        cols   = ["Name", "Email", "Course", "Completed", "Total", "Rate"]
        widths = [40, 60, 35, 18, 18, 19]
        pdf.table_header(cols, widths)
        for i, row in at_risk.iterrows():
            name  = str(row["student_name"])[:25] + "..." if len(str(row["student_name"])) > 25 else str(row["student_name"])
            email = str(row["email"])[:35] + "..."        if len(str(row["email"])) > 35        else str(row["email"])
            pdf.table_row([
                s(name), s(email), s(row["course"]),
                s(str(row["done"])), s(str(row["total"])), s(f"{row['rate']}%")
            ], widths, shade=(i % 2 == 0))

    return bytes(pdf.output())